services:
  db:
    image: postgres:18.0
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: my-task-board-app-back
    volumes:
      - ./postgres:/var/lib/postgresql
